# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "859a48fdfd50c97762ddebf86fbf5301"
application_url = "https://tiger-trips-race-recall.trycloudflare.com"
embedded = true
name = "App  Development"
handle = "app-development-23"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quick-start-v2.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://tiger-trips-race-recall.trycloudflare.com/auth/callback",
  "https://tiger-trips-race-recall.trycloudflare.com/auth/shopify/callback",
  "https://tiger-trips-race-recall.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
